import Navbar from '@/components/Navbar';
import './globals.css';
import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';
import AuthContext from '@/context/AuthContext';
import SwrContext from '@/context/SwrContext';

const openSans = Open_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={openSans.className}>
      <body className="bg-neutral-50 w-full max-w-screen-xl overflow-auto mx-auto flex flex-col justify-center items-center">
        <AuthContext>
          <SwrContext>
            <header className="sticky top-0 bg-white z-10 border-b w-full grow">
              <Navbar />
            </header>
            <main className="">{children}</main>
          </SwrContext>
        </AuthContext>
      </body>
    </html>
  );
}
